apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-library
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: lscr.io/linuxserver/calibre-web:latest
          ports:
            - containerPort: 8083
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: TZ
              value: America/Denver
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /books
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: library
          persistentVolumeClaim:
            claimName: calibre-web-library
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  selector:
    app: calibre-web
