apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cluster
  namespace: authentik
spec:
  instances: 1

  bootstrap:
    initdb:
      database: authentik
      owner: authentik

  storage:
    size: 5Gi
