repositories:
  - name: authentik
    url: https://charts.goauthentik.io

releases:
  # https://github.com/goauthentik/helm
  - name: authentik
    namespace: authentik
    chart: authentik/authentik
    version: 2026.5.4
    values:
      - authentik-values.yaml
